In [1]:
import numpy as np
import pandas as pd

In [4]:
mices=pd.DataFrame(columns=['weight'])
mices['weight']=[20, 30, 15, 6, 40, 150, 99, 1]
mices

weight
0      20
1      30
2      15
3       6
4      40
5     150
6      99
7       1

In [5]:
mices.loc[2]

weight    15
Name: 2, dtype: int64

In [10]:
mices['weight'][2:]

2     15
3      6
4     40
5    150
6     99
7      1
Name: weight, dtype: int64

In [13]:
mices['weight']=np.random.randint(5, 60, size=8)

In [14]:
mices

weight
0      42
1      24
2      49
3      13
4      37
5      48
6      34
7       8

In [15]:
mices['is_obese']=(mices['weight']>=20).astype(int)

In [16]:
mices

weight  is_obese
0      42         1
1      24         1
2      49         1
3      13         0
4      37         1
5      48         1
6      34         1
7       8         0

In [17]:
test_mices=pd.DataFrame(columns=['weight'])
test_mices['weight']=[10, 30]
test_mices

weight
0      10
1      30

In [18]:
from sklearn.linear_model import LogisticRegression

In [51]:
clf = LogisticRegression(max_iter=3000)
clf.fit(np.array(mices['weight'].tolist()).reshape(-1, 1), mices['is_obese'])


LogisticRegression(max_iter=3000)

In [25]:
mices['weight']

0    42
1    24
2    49
3    13
4    37
5    48
6    34
7     8
Name: weight, dtype: int64

In [27]:
mices['weight'].tolist()

[42, 24, 49, 13, 37, 48, 34, 8]

In [28]:
np.array(mices['weight'].tolist())

array([42, 24, 49, 13, 37, 48, 34,  8])

In [33]:
np.array(mices['weight'].tolist()).reshape(-1, 1)

array([[42],
       [24],
       [49],
       [13],
       [37],
       [48],
       [34],
       [ 8]])

In [52]:
clf.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 3000,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [35]:
clf

LogisticRegression()

In [38]:
test_prediction = clf.predict_proba(np.array(test_mices['weight'].tolist()).reshape(-1, 1))

In [39]:
print(test_prediction)

[[0.99095164 0.00904836]
 [0.00187028 0.99812972]]


In [53]:
test_prediction = clf.predict_proba(np.array(test_mices['weight'].tolist()).reshape(-1, 1))

In [54]:
print(test_prediction)

[[0.99095164 0.00904836]
 [0.00187028 0.99812972]]
