In [15]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np


In [16]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

[[-0.49079728 -1.87629612  0.73574267 -1.10730433]]
[6.18260703]


In [31]:
print(y.shape)

(150,)


In [39]:
y[100]

2

In [33]:
y_col=y.reshape(-1, 1)
print(y_col.shape)

(150, 1)


In [38]:
y_col[100,0]

2

In [42]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [43]:
enc = OneHotEncoder()
y_one_hot=enc.fit_transform(y_col).toarray()
print(y_one_hot.shape)


(150, 3)


In [46]:
target_df=pd.DataFrame(data=y_one_hot, columns=iris['target_names'])
target_df.head()

setosa  versicolor  virginica
0     1.0         0.0        0.0
1     1.0         0.0        0.0
2     1.0         0.0        0.0
3     1.0         0.0        0.0
4     1.0         0.0        0.0

In [53]:
data_df=pd.DataFrame(data=X, columns=iris['feature_names'])
data_df['target']=y
data_df=pd.concat([data_df, target_df], axis=1)
pd.set_option("max_rows", 150)

data_df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  setosa  versicolor  virginica  
0       0     1.0         0.0        0.0  
1       0     1.0         0.0        0.0  
2       0     1.0         0.0        0.0  
3       0     1.0         0.0        0.0  
4       0     1.0         0.0        0.0

In [55]:
y_versicolor=data_df['versicolor'].values
X=data_df[['sepal length (cm)','sepal width (cm)', 'petal length (cm)']].values
print(y_versicolor.shape)
print(X.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y_versicolor, test_size = 0.2, random_state = 0)

model=LogisticRegression()
model.fit(X_train, y_train)

print(model.coef_)
print(model.intercept_)

(150,)
(150, 3)
[[-0.41714509 -1.97989723  0.24251844]]
[6.58978406]


In [58]:
y_test_pred_probability=model.predict_proba(X_test) # логістична регресія
y_test_pred_probability_1=y_test_pred_probability[:,1] # : - взяти всі рядочки (або колонки)
print(y_test_pred_probability_1)

[0.46592151 0.66845674 0.02458908 0.33867356 0.13425908 0.24660901
 0.108099   0.2309539  0.34832131 0.37088093 0.56354687 0.21010665
 0.41127998 0.36591396 0.36431917 0.09601303 0.36274831 0.55350298
 0.26645604 0.04439895 0.47462175 0.35558305 0.1566487  0.3434786
 0.40705841 0.098483   0.06910751 0.33283553 0.6793107  0.13710305]


In [57]:
model.predict(X_test)

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])

In [59]:
len(data_df)

150

In [62]:
y_all_probability_1=model.predict_proba(X)[:,1]
data_df['versicolor_proba_1']=y_all_probability_1
data_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  setosa  versicolor  virginica  versicolor_proba_1  
0       0     1.0         0.0        0.0            0.106427  
1       0     1.0         0.0        0.0            0.258382  
2       0     1.0         0.0        0.0            0.199217  
3       0     1.0         0.0        0.0            0.249181  
4       0     1.0         0.0        0.0            0.092453

In [63]:
# -0.41714509 -1.97989723  0.24251844
# 6.58978406
logits=(-0.41714509*5.1)+(-1.97989723*3.5)+(0.24251844*1.4)+6.58978406
print(logits)

-2.127770387999999


In [65]:
probab_1_for_flower0=1/(1+1/np.exp(logits))
print(probab_1_for_flower0)

0.10642684216430526


In [64]:
np.exp(1)

2.718281828459045

In [85]:
coef=model.coef_[0]
bias=model.intercept_[0]
logits_all=coef[0]*data_df['sepal length (cm)']+coef[1]*data_df['sepal width (cm)']+coef[2]*data_df['petal length (cm)']+bias

In [86]:
data_df['logits']=logits_all
data_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  setosa  versicolor  virginica  versicolor_proba_1    logits  \
0       0     1.0         0.0        0.0            0.106427 -2.127770   
1       0     1.0         0.0        0.0            0.258382 -1.054393   
2       0     1.0         0.0        0.0            0.199217 -1.391195   
3       0     1.0         0.0        0.0            0.249181 -1.102987   
4       0     1.0         0.0        0.0            0.092453 -2.284046   

   prob_manual_versicolor  prob_man_ver  
0                0.106458             0  
1                0.114659             0  
2                0.123404             0  
3                0.127988             0  
4                0.110492             0

In [87]:
data_df['prob_manual_versicolor']=data_df['logits'].apply(lambda x: 1/(1+1/np.exp(x)))
data_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  setosa  versicolor  virginica  versicolor_proba_1    logits  \
0       0     1.0         0.0        0.0            0.106427 -2.127770   
1       0     1.0         0.0        0.0            0.258382 -1.054393   
2       0     1.0         0.0        0.0            0.199217 -1.391195   
3       0     1.0         0.0        0.0            0.249181 -1.102987   
4       0     1.0         0.0        0.0            0.092453 -2.284046   

   prob_manual_versicolor  prob_man_ver  
0                0.106427             0  
1                0.258382             0  
2                0.199217             0  
3                0.249181             0  
4                0.092453             0

In [88]:
# DZ : calculate logistic regression for 4 features (we did for 3)

In [ ]:
"""
    Algorithm GRADIENT DESCENT (trying to minimize Loss function (which for example, = mean_square_error(GT, preds)))
    
    Algorithm of Logistic Regression tries to find optimal: Coeficients, Bias (Intercept)
    --> logits = sum(coef[i] * features[i]) + intercept 
    --> logistic_function(logits) = 1/(1+1/(np.exp(x)))
    --> probabilities_of_being = 1
"""

In [92]:
#MSE - mean square error

GT=y_train
first_step_probab=0
MSE=pd.DataFrame(data=GT, columns=['GT'])
MSE['step_pred']=first_step_probab
MSE.head()

GT  step_pred
0  0.0          0
1  1.0          0
2  0.0          0
3  0.0          0
4  0.0          0

In [93]:
MSE['dif']=MSE['GT']-MSE['step_pred']
MSE['dif_square']=MSE['dif']*MSE['dif']
MSE.head()

GT  step_pred  dif  dif_square
0  0.0          0  0.0         0.0
1  1.0          0  1.0         1.0
2  0.0          0  0.0         0.0
3  0.0          0  0.0         0.0
4  0.0          0  0.0         0.0

In [94]:
mse_loss=MSE['dif_square'].mean()
print(mse_loss)

0.30833333333333335


In [ ]:
gt=0 pred=1 diff=0-1=-1 - bad situation
gt=1 pred=0 diff=1-0=1 - bad situation
# якщо візьмемо середнє між -1 і 1, то loss function буде 0. Ми нічого не втрачаємо, але сітуації погані
# а тепер візьмемо квадрати різниць і знайдемо середнє для них:
# ((-1)^2+(1^2))/2=1